service: serverless-chrome

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    CHROME_PATH: ./headless-chrome/headless_shell

custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack
  - content-handling

functions:
  run:
    description: Run headless Chromium
    memorySize: 1536
    timeout: 30
    handler: handler.run

    events:
      - http:
          path: chrome
          method: get
          contentHandling: CONVERT_TO_BINARY
          integration: lambda
          request:
            template:
              application/json: >
                {
                  "url": "$input.params('url')"
                }
          response:
            template: $input.path('$')
            headers:
              Content-Type: "'application/pdf'"